# post_install.ps1 - run by Inno Setup after files are copied
# Args: -InstallDir <path> -DataDir <path> -Port <number> -ServiceName <name>
param(
    [string]$InstallDir  = "C:\Program Files\OverallDashboard",
    [string]$DataDir     = "C:\ProgramData\OverallDashboard",
    [int]   $Port        = 8092,
    [string]$ServiceName = "OverallDashboard"
)

# -- Log to file from the very first line (before ErrorActionPreference) -------
$LogDir    = "C:\ProgramData\OverallDashboard\logs"
$null      = New-Item -ItemType Directory -Force -Path $LogDir
$LogFile   = Join-Path $LogDir "install-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"
function Log($msg) {
    $line = "$(Get-Date -Format 'HH:mm:ss')  $msg"
    Add-Content -Path $LogFile -Value $line
    Write-Host $line
}
Log "=== post_install.ps1 started ==="
Log "InstallDir=$InstallDir  DataDir=$DataDir  Port=$Port  ServiceName=$ServiceName"

$ErrorActionPreference = "Stop"
trap {
    Log "ERROR: $_"
    Log "=== FAILED ==="
    exit 1
}

$PythonInstaller = Join-Path $InstallDir "installer\python-installer.exe"
$PythonDir       = Join-Path $InstallDir "python"
$PythonExe       = Join-Path $PythonDir  "python.exe"
$VenvDir         = Join-Path $InstallDir ".venv"
$WinSwExe        = Join-Path $InstallDir "nssm\WinSW.exe"
$WheelsDir       = Join-Path $InstallDir "installer\wheels"

# -- 1. Create data & log directories -----------------------------------------
New-Item -ItemType Directory -Force -Path $DataDir                  | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DataDir "exports") | Out-Null
Log "[1/7] Data directory ready: $DataDir"

# -- 2. Install Python app-local -----------------------------------------------
Log "[2/7] Installing Python to $PythonDir ..."
if (-not (Test-Path $PythonExe)) {
    if (-not (Test-Path $PythonInstaller)) {
        throw "Python installer not found at: $PythonInstaller"
    }
    $installArgs = "/quiet InstallAllUsers=0 PrependPath=0 Include_test=0 " +
                   "Include_launcher=0 Include_doc=0 " +
                   "TargetDir=`"$PythonDir`""
    Log "      Running: $PythonInstaller $installArgs"
    $proc = Start-Process -FilePath $PythonInstaller -ArgumentList $installArgs -Wait -PassThru
    Log "      Python installer exit code: $($proc.ExitCode)"
    if (-not (Test-Path $PythonExe)) {
        throw "Python install finished but python.exe not found at: $PythonExe"
    }
    Log "      Python installed OK"
} else {
    Log "      Python already present, skipping"
}

# -- 3. Create venv and install dependencies (offline wheels) ------------------
Log "[3/7] Creating virtual environment at $VenvDir ..."
if (-not (Test-Path "$VenvDir\Scripts\python.exe")) {
    & $PythonExe -m venv $VenvDir
    if ($LASTEXITCODE -ne 0) { throw "venv creation failed (exit $LASTEXITCODE)" }
}
Log "      Installing dependencies from bundled wheels..."
if (-not (Test-Path $WheelsDir)) { throw "Wheels folder not found: $WheelsDir" }
& "$VenvDir\Scripts\pip.exe" install --no-index --find-links $WheelsDir -r (Join-Path $InstallDir "requirements.txt") 2>&1 | ForEach-Object { Log "pip: $_" }
if ($LASTEXITCODE -ne 0) { throw "pip install failed (exit $LASTEXITCODE)" }
Log "      Dependencies installed OK"

$VenvPython = "$VenvDir\Scripts\python.exe"

# -- 4. Write production config.py ---------------------------------------------
Log "[4/7] Writing production config..."
$InstallDirEsc = $InstallDir -replace '\\','\\'
$DataDirEsc    = $DataDir    -replace '\\','\\'
$cfgLines = @(
    '# Production configuration - generated by installer. Do not edit manually.',
    'import os',
    'from pathlib import Path',
    '',
    "SERVER_HOST  = '0.0.0.0'",
    "SERVER_PORT  = $Port",
    'DEBUG_MODE   = False',
    '',
    "BASE_DIR                 = Path(r'$InstallDirEsc')",
    "DATABASE_PATH            = Path(r'$DataDirEsc') / 'dashboards.db'",
    "PORTFOLIO_DATABASE_PATH  = Path(r'$DataDirEsc') / 'portfolio.db'",
    "EXCEL_OUTPUT_FOLDER      = Path(r'$DataDirEsc') / 'exports'",
    '',
    'DB_TIMEOUT = 30',
    '',
    'EXCEL_PROJECT_NAME_ROW = 3',
    "EXCEL_PROJECT_NAME_COL = 'C'",
    'EXCEL_MANAGER_ROW      = 5',
    "EXCEL_MANAGER_COL      = 'C'",
    'EXCEL_HEADER_ROW       = 10',
    'EXCEL_DATA_START_ROW   = 11',
    '',
    'EXCEL_COLUMNS = {',
    "    'reference_id': 'A',",
    "    'name':         'B',",
    "    'phase':        'C',",
    "    'owner':        'D',",
    "    'start_date':   'E',",
    "    'status':       'F',",
    "    'end_date':     'G',",
    "    'date_closed':  'H',",
    "    'result':       'I',",
    '}',
    '',
    'DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)',
    'EXCEL_OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)'
)
$cfgLines -join "`r`n" | Set-Content -Encoding UTF8 -Path (Join-Path $InstallDir 'config.py')
Log "      Config written (port $Port)"

# -- 5. Verify database --------------------------------------------------------
Log "[5/7] Checking database..."
$dbPath = Join-Path $DataDir "dashboards.db"
if (Test-Path $dbPath) {
    Log "      DB found ($([math]::Round((Get-Item $dbPath).Length/1MB,2)) MB)"
} else {
    Log "      WARNING: DB not found - will be created on first start"
}

# -- 6. Register Windows service via WinSW ------------------------------------
Log "[6/7] Registering Windows service '$ServiceName'..."

$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    Log "      Stopping existing service..."
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 3
    sc.exe delete $ServiceName | Out-Null
    # Wait for service to be fully deleted (up to 15s)
    $waited = 0
    while ((Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) -and $waited -lt 15) {
        Start-Sleep -Seconds 1; $waited++
    }
    Log "      Old service removed (waited ${waited}s)"
}

$xmlPath      = Join-Path $InstallDir "nssm\$ServiceName.xml"
$winswService = Join-Path $InstallDir "nssm\$ServiceName.exe"

# Build XML via array join - avoids here-string PS5.1 parsing issues
$xmlLines = @(
    '<service>',
    "  <id>$ServiceName</id>",
    '  <name>Overall Programs Dashboard</name>',
    "  <description>Web-based project dashboard (Flask, port $Port)</description>",
    "  <executable>$VenvPython</executable>",
    '  <arguments>server.py</arguments>',
    "  <workingdirectory>$InstallDir</workingdirectory>",
    "  <logpath>$LogDir</logpath>",
    '  <logmode>rotate</logmode>',
    '  <sizeThreshold>5120</sizeThreshold>',
    '  <startmode>Automatic</startmode>',
    '  <onfailure action="restart" delay="5 sec"/>',
    '  <onfailure action="restart" delay="10 sec"/>',
    '  <onfailure action="restart" delay="20 sec"/>',
    '</service>'
)
$xmlLines -join "`r`n" | Set-Content -Encoding UTF8 -Path $xmlPath
Copy-Item $WinSwExe $winswService -Force

Log "      Running WinSW install..."
$out = & $winswService install 2>&1
Log "      WinSW output: $out  (exit $LASTEXITCODE)"
if ($LASTEXITCODE -ne 0) { throw "WinSW install failed (exit $LASTEXITCODE)" }

# -- 7. Open firewall & register backup task -----------------------------------
Log "[7/7] Firewall + backup task..."
$ruleName = "Overall Programs Dashboard (port $Port)"
Remove-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Protocol TCP `
    -LocalPort $Port -Action Allow -Profile Domain,Private | Out-Null

$backupScript = Join-Path $InstallDir "installer\backup_db.ps1"
$taskName     = "OverallDashboard_NightlyBackup"
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
$action    = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$backupScript`" -DataDir `"$DataDir`" -BackupRoot `"$DataDir\backups`""
$trigger   = New-ScheduledTaskTrigger -Daily -At "01:00"
$settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -RunOnlyIfNetworkAvailable:$false
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
    -Settings $settings -Principal $principal | Out-Null

# -- Start service -------------------------------------------------------------
Log "Starting service..."
& $winswService start 2>&1 | ForEach-Object { Log "WinSW start: $_" }
Start-Sleep -Seconds 5

$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq 'Running') {
    Log "========================================="
    Log "  Installation complete!"
    Log "  Dashboard: http://localhost:$Port"
    Log "  Logs:      $LogDir"
    Log "  Log file:  $LogFile"
    Log "========================================="
    Log "=== SUCCESS ==="
} else {
    $status = if ($svc) { $svc.Status } else { "not found" }
    throw "Service did not start (status: $status). Check $LogDir for WinSW logs."
}
