# post_install.ps1 — run by Inno Setup after files are copied
# Args: -InstallDir <path> -DataDir <path> -Port <number> -ServiceName <name>
param(
    [string]$InstallDir  = "C:\Program Files\OverallDashboard",
    [string]$DataDir     = "C:\ProgramData\OverallDashboard",
    [int]   $Port        = 8092,
    [string]$ServiceName = "OverallDashboard"
)

$ErrorActionPreference = "Stop"
$PythonExe  = Join-Path $InstallDir ".venv\Scripts\python.exe"
$WinSwExe   = Join-Path $InstallDir "nssm\WinSW.exe"
$ServerPy   = Join-Path $InstallDir "server.py"
$LogDir     = Join-Path $DataDir    "logs"

# ── 1. Create data & log directories ─────────────────────────────────────────
New-Item -ItemType Directory -Force -Path $DataDir  | Out-Null
New-Item -ItemType Directory -Force -Path $LogDir   | Out-Null
Write-Host "[1/5] Data directory ready: $DataDir"

# ── 2. Write prod_config.py (overrides dev config.py) ────────────────────────
$prodConfig = @"
# Production configuration — generated by installer. Do not edit manually.
# Re-run the installer to change port or paths.
import os
from pathlib import Path

SERVER_HOST  = '0.0.0.0'          # listen on all interfaces (intranet access)
SERVER_PORT  = $Port
DEBUG_MODE   = False

BASE_DIR     = Path(r'$($InstallDir -replace "\\","\\\\")' )
DATABASE_PATH        = Path(r'$($DataDir -replace "\\","\\\\")') / 'dashboards.db'
PORTFOLIO_DATABASE_PATH = Path(r'$($DataDir -replace "\\","\\\\")') / 'portfolio.db'
EXCEL_OUTPUT_FOLDER  = Path(r'$($DataDir -replace "\\","\\\\")') / 'exports'

DB_TIMEOUT = 30

EXCEL_PROJECT_NAME_ROW = 3
EXCEL_PROJECT_NAME_COL = 'C'
EXCEL_MANAGER_ROW      = 5
EXCEL_MANAGER_COL      = 'C'
EXCEL_HEADER_ROW       = 10
EXCEL_DATA_START_ROW   = 11

EXCEL_COLUMNS = {
    'reference_id': 'A',
    'name':         'B',
    'phase':        'C',
    'owner':        'D',
    'start_date':   'E',
    'status':       'F',
    'end_date':     'G',
    'date_closed':  'H',
    'result':       'I',
}

DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
EXCEL_OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)
"@
$prodConfig | Set-Content -Encoding UTF8 -Path (Join-Path $InstallDir "config.py")
Write-Host "[2/5] Production config written (port $Port)"

# ── 3. Verify database is present ────────────────────────────────────────────
Write-Host "[3/5] Checking database..."
$dbPath = Join-Path $DataDir "dashboards.db"
if (Test-Path $dbPath) {
    $sizeMB = [math]::Round((Get-Item $dbPath).Length / 1MB, 2)
    Write-Host "      Database found ($sizeMB MB): $dbPath"
} else {
    Write-Host "      WARNING: Database not found at $dbPath"
    Write-Host "      A fresh empty database will be created on first server start."
}

# ── 4. Register Windows Service via WinSW ────────────────────────────────────
Write-Host "[4/5] Registering Windows service '$ServiceName'..."

# Remove existing service if upgrading
$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
    sc.exe delete $ServiceName | Out-Null
    Start-Sleep -Seconds 2
}

# Write WinSW XML config
$winswXml = @"
<service>
  <id>$ServiceName</id>
  <name>Overall Programs Dashboard</name>
  <description>Web-based project dashboard (Flask, port $Port)</description>
  <executable>$PythonExe</executable>
  <arguments>server.py</arguments>
  <workingdirectory>$InstallDir</workingdirectory>
  <logpath>$LogDir</logpath>
  <logmode>rotate</logmode>
  <sizeThreshold>5120</sizeThreshold>
  <startmode>Automatic</startmode>
  <onfailure action="restart" delay="5 sec"/>
  <onfailure action="restart" delay="10 sec"/>
  <onfailure action="restart" delay="20 sec"/>
</service>
"@
$xmlPath = Join-Path $InstallDir "nssm\$ServiceName.xml"
$winswXml | Set-Content -Encoding UTF8 -Path $xmlPath

# WinSW requires the exe to be named after the service
$winswService = Join-Path $InstallDir "nssm\$ServiceName.exe"
Copy-Item $WinSwExe $winswService -Force

& $winswService install
if ($LASTEXITCODE -ne 0) { throw "WinSW service install failed" }

# ── 5. Open firewall port ────────────────────────────────────────────────────
Write-Host "[5/6] Opening firewall port $Port..."
$ruleName = "Overall Programs Dashboard (port $Port)"
Remove-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
New-NetFirewallRule `
    -DisplayName $ruleName `
    -Direction   Inbound  `
    -Protocol    TCP      `
    -LocalPort   $Port    `
    -Action      Allow    `
    -Profile     Domain,Private | Out-Null

# ── 6. Register nightly backup Task Scheduler job ────────────────────────────
Write-Host "[6/6] Registering nightly backup task..."
$backupScript = Join-Path $InstallDir "installer\backup_db.ps1"
$taskName     = "OverallDashboard_NightlyBackup"

# Remove existing task if upgrading
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

$action  = New-ScheduledTaskAction `
    -Execute    "powershell.exe" `
    -Argument   "-NoProfile -ExecutionPolicy Bypass -File `"$backupScript`" -DataDir `"$DataDir`" -BackupRoot `"$DataDir\backups`""
$trigger = New-ScheduledTaskTrigger -Daily -At "01:00"
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -RunOnlyIfNetworkAvailable:$false
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest

Register-ScheduledTask `
    -TaskName  $taskName `
    -Action    $action   `
    -Trigger   $trigger  `
    -Settings  $settings `
    -Principal $principal `
    -Description "Nightly SQLite backup of Overall Programs Dashboard databases" | Out-Null

Write-Host "  ✓ Backup scheduled: daily at 01:00, keeps 30 daily + 4 weekly"
Write-Host "  ✓ Backup location: $DataDir\backups"

# ── Start service ────────────────────────────────────────────────────────────
Write-Host "Starting service..."
& $winswService start
Start-Sleep -Seconds 5

$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq 'Running') {
    Write-Host ""
    Write-Host "========================================="
    Write-Host "  Installation complete!"
    Write-Host "  Dashboard: http://localhost:$Port"
    Write-Host "  Service:   $ServiceName (auto-start)"
    Write-Host "  Data:      $DataDir"
    Write-Host "  Logs:      $LogDir"
    Write-Host "  Backups:   $DataDir\backups (daily 01:00)"
    Write-Host "========================================="
} else {
    throw "Service did not start. Check logs at $LogDir"
}
